# Intro to Python and Numpy

Welcome to the first notebook of this course! In this notebook, we are
going to learn how to represent different kinds of data in Python. We
are also taking our first look at creating arrays in Numpy and we are
going to analyze some actual neuroscience data. Finally, we are going to
explore the differences in performance between Numpy and built-in Python
functions.

Execute the cell below to install the packages required for this
notebook.

In [1]:
%pip install numpy

## 1 Storing Data in Variables

In the first section, we are going to learn how to represent different
kinds of data and store them in variables. We are going to encounter
four basic data types: integers, floating-point numbers, Boolean values
and text strings. We are also going to use lists which are collections
of data. Data can be assigned to a variable using the `=` operator which
takes the value on the right and assigns it to the variable on the left.
In this sense, a variable is simply a container that we can use to store
and access data. The data type of a variable can be determined with the
`type()` function. We can also convert variables from one type to
another - for example, the `int()` function will try to convert a
variable to an integer. Finally, Python provides operators for the
arithmetic operations like addition `+`, subtraction `-`, multiplication
`*` and division `/`. Let’s test how this works!

| Code | Description |
|------------------------------------|------------------------------------|
| `x = 3.14` | Assign the floating-point number `3.14` to the variable `x` |
| `x = True` | Assign the boolean value `True` to the variable `x` |
| `x = "hello"` | Assign the string `"hello"` to the variable `x` |
| `x = [1,2,3]` | Assign the list of integers `[1,2,3]` to the variable `x` |
| `type(x)` | Get the data type of variable `x` |
| `int(x)` | Convert the variable `x` to an integer, if possible |
| `+`, `-`, `*`, `/` | Add, subtract, multiply, divide values |

------------------------------------------------------------------------

<span class="theorem-title">**Example 1**</span> Assign the integer
value `1` to a variable called `one` and print its `type()`.

In [2]:
one = 1
type(one)

int

<span class="theorem-title">**Exercise 1**</span> Subtract 0.5 from the
variable `one`

*Solution.*

In [3]:
one - 0.5

0.5

<span class="theorem-title">**Exercise 2**</span> Assign the floating
value `0.001` to a variable called `small` and print its type.

*Solution.*

In [5]:
small = 0.001
type(small)

float

<span class="theorem-title">**Exercise 3**</span> Assign the Boolean
value `False` to a variable called `this_is_false` and convert it to an
integer.

*Solution.*

In [7]:
this_is_false = False
int(this_is_false)

0

<span class="theorem-title">**Exercise 4**</span> Assign the Boolean
value `True` to a variable called `this_is_true` and convert it to an
integer.

*Solution.*

In [9]:
this_is_true = True
int(this_is_true)

1

<span class="theorem-title">**Exercise 5**</span> Assign the string
value `"goodbye"` to a variable called `goodbye` and print its type

*Solution.*

In [11]:
goodbye = "goodbye"
type(goodbye)

str

<span class="theorem-title">**Exercise 6**</span> Add the string
`"hello"` to the variable `goodbye`

*Solution.*

In [13]:
goodbye + "hello"

'goodbyehello'

<span class="theorem-title">**Exercise 7**</span> Assign a list with the
number 0 through 6 to a variable called `dice` and print its type

*Solution.*

In [15]:
dice = [0,1,2,3,4,5,6]
type(dice)

list

<span class="theorem-title">**Exercise 8**</span> Multiply the list
`dice` by 2. Try to add 1 to it.

*Solution.*

In [17]:
dice * 2
dice + 1

## 2 Analyzing Neural Spiking Data with Numpy

Numpy offers many useful functions for data analysis - let’s test them
on some actual neuroscience data! In this section, we are going to load
and analyze the spiking of a neuron in the primary visual cortex of a
mouse. The spikes are represented as a sorted list of time points where
spikes were observed. For example, `[0.05, 0.24, 1.5]` indicates that a
spike was observed 50, 240 and 1500 milliseconds after the start of the
recording. Using the functions below, we can answer some interesting
questions about the firing behavior of a given neuron.

| Code | Description |
|------------------------------------|------------------------------------|
| `import numpy as np` | Import the module `numpy` under the alias `np` |
| `x = np.load("data.npy")` | Load the file `"data.npy"` into an array and assign it to the variable `x` |
| `np.size(x)` | Get the total number of element stored in the array `x` |
| `np.min(x)` | Get the minimum value of the array `x` |
| `np.max(x)` | Get the maximum value of the array `x` |
| `np.mean(x)` | Compute the mean of all values in the array `x` |
| `np.std(x)` | Compute the standard deviation of all values in the array `x` |
| `np.diff(x)` | Compute the difference between consecutive elements in the array `x` |

------------------------------------------------------------------------

<span class="theorem-title">**Exercise 9**</span> Import the Numpy
module under the alias `np`.

*Solution.*

In [18]:
import numpy as np

<span class="theorem-title">**Exercise 10**</span> Load the file
`"spikes.npy"` into a Numpy array.

*Solution.*

In [20]:
spikes = np.load("spikes.npy")

<span class="theorem-title">**Exercise 11**</span> What is the total
number of spikes in this recording?

*Solution.*

In [22]:
np.size(spikes)

721

<span class="theorem-title">**Exercise 12**</span> What is the duration
of the recording (assuming the recording stopped after the last spike
was recorded)?

*Solution.*

In [24]:
np.max(spikes)

np.float64(298.4843451836275)

<span class="theorem-title">**Exercise 13**</span> Compute the neuron’s
average firing rate (the total number of spikes divided by the duration
of the recording).

*Solution.*

In [26]:
np.size(spikes)/np.max(spikes)

np.float64(2.415537067970653)

<span class="theorem-title">**Exercise 14**</span> Compute the
inter-spike intervals (i.e. the time differences between subsequent
spikes).

*Solution.*

In [28]:
isi = np.diff(spikes)

<span class="theorem-title">**Exercise 15**</span> What is the average
inter-spike interval for this neuron?

*Solution.*

In [30]:
np.mean(isi)

np.float64(0.4144865856420776)

<span class="theorem-title">**Exercise 16**</span> What is the standard
deviation of inter-spike intervals for this neuron?

*Solution.*

In [32]:
np.std(isi)

np.float64(0.47663480650055273)

<span class="theorem-title">**Exercise 17**</span> What is the shortest
time between two spikes?

*Solution.*

In [34]:
np.min(isi)

np.float64(0.0005666682648097776)

## 3 Creating Arrays in Numpy

Numpy also offers many functions for generating arrays. The simplest way
to create an array is to convert a list but there are other functions
for specific purposes like generating arrays of random numbers or
numbers within a certain range. Like variables, Numpy arrays can have
different data types. The type of an array is stored in the `.dtype`
attribute. In this section, we are going to create and explore different
kinds of arrays.

| Code | Description |
|------------------------------------|------------------------------------|
| `x = np.array([2,5,3])` | Create an array from the list `[2,5,3]` and assign it to the variable `x` |
| `x = np.random.randn(100)` | Create an array with 100 normally-distributed random numbers and assign it to the variable `x` |
| `x = np.arange(2,7)` | Create an array with all integers between 2 and (not including) 7 and assign it to the variable `x` |
| `x = np.arange(2,7,0.3)` | Create an array with evenly spaced values between 2 and 7 with a step size of 0.3 and assign it to the variable `x` |
| `x = np.linspace(2,3,10)` | Create an array with 10 evenly spaced values between 2 and 3 and assign it to the variable `x` |
| `x.dtype` | Get the data type of the numpy array `x` |

------------------------------------------------------------------------

<span class="theorem-title">**Example 2**</span> Create an array from
the list `[1, 2, 3]`, assign it to the variable `a` and print its type.

In [36]:
a = np.array([1,2,3])
a.dtype

dtype('int64')

<span class="theorem-title">**Exercise 18**</span> Multiply the array
`a` by 2 and add 1 to it

*Solution.*

In [37]:
a * 2 + 1

array([3, 5, 7])

<span class="theorem-title">**Exercise 19**</span> Create an array from
the list `[0.1, 0.2, 0.3]`, assign it to the variable `b` and print its
type.

*Solution.*

In [39]:
b = np.array([0.1, 0.2, 0.3])
b.dtype

dtype('float64')

<span class="theorem-title">**Exercise 20**</span> Create an array with
from the list `[1, True, "a"]`, assign it to the variable `c` and print
it’s type.

*Solution.*

In [41]:
c = np.array([1, True, "a"])
c.dtype

dtype('<U21')

<span class="theorem-title">**Exercise 21**</span> Make an array
containing the integers from 1 to 15.

*Solution.*

In [43]:
np.arange(1, 15+1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

<span class="theorem-title">**Exercise 22**</span> Create an array that
contains all even numbers up to and including 100.

*Solution.*

In [45]:
np.arange(0, 100+2, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

<span class="theorem-title">**Exercise 23**</span> Make an array of only
6 evenly-spaced numbers between 1 and 10.

*Solution.*

In [47]:
np.linspace(1, 10, 6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

<span class="theorem-title">**Exercise 24**</span> Create an array of 10
normally-distributed random numbers and compute its mean and standard
deviation.

*Solution.*

In [49]:
x = np.random.randn(10)
print(np.mean(x))
print(np.std(x))

0.11793708669506826
1.378158681821577

<span class="theorem-title">**Exercise 25**</span> Now, create arrays
with of 100 and 1000 normally-distributed random numbers and compute
their means and standard deviations.

*Solution.*

In [51]:
x = np.random.randn(100)
print(np.mean(x))
print(np.std(x))

x = np.random.randn(1000)
print(np.mean(x))
print(np.std(x))

-0.10221800064240914
1.1031089475978166
-0.024782693827162455
0.9827439275545455

<span class="theorem-title">**Exercise 26**</span> Assume we recorded a
signal with a duration of 20 seconds at a sampling rate of 100 Hz.
Create an array of time points for this signal using both `np.arange()`
and `np.linspace()`. The array should start at 0, end at 20 and contain
150 points per second. Are the arrays generated with the two methods
identical?

*Solution.*

In [53]:
t1 = np.linspace(0, 20, 100*20+1)
t2 = np.arange(0, 20+1/100, 1/100)

The array created with `np.arange()` may be longer because of rounding
errors.

## 4 Quantifying Numpy’s Performance

One of the key advantages of Numpy is that it is a lot faster than basic
Python. How much faster? Let’s find out! The code below creates an array
of ten thousand random numbers as well as a list with exactly the same
data. We can use these to test how Numpy compares to basic Python with
respect to performance.

In [55]:
my_array = np.random.randn(10000)
my_list = list(my_array)

To time our code, we are going to use the `%%timeit` command. Adding
`%%timeit` at the top of a cell makes it so that running that cell
displays the time it took to run the code. Per default, the code is
executed ten times in a loop and the result is averaged over all loops.
This procedure is repeated seven times so that we get one average
duration for each run. The reported numbers are the average duration
across the seven runs and its standard deviation.

------------------------------------------------------------------------

<span class="theorem-title">**Example 3**</span> Estimate the time for
computing the sum of `my_list` using Python’s built-in `sum()` method
with `%%timeit`.

In [56]:
%%timeit
sum(my_list)

704 μs ± 31.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

<span class="theorem-title">**Exercise 27**</span> Use `%%timeit` to
estimate how long it takes to compute `np.sum()` of `my_array`.

*Solution.*

In [57]:
%%timeit
np.sum(my_array)

7.75 μs ± 157 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

<span class="theorem-title">**Exercise 28**</span> Use `%%timeit` to
estimate how long it takes for Python’s built-in `max()` function to
find the maximum of `my_list`.

*Solution.*

In [59]:
%%timeit
max(my_list)

141 μs ± 1.18 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

<span class="theorem-title">**Exercise 29**</span> Use `%%timeit` to
estimate how long it takes for the `np.max()` function to find the
maximum of `my_array`.

*Solution.*

In [61]:
%%timeit
np.max(my_array)

8.21 μs ± 154 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

<span class="theorem-title">**Exercise 30**</span> The code below
estimates the time it takes to multiply every element of `my_list` by 2.
Use `%%timeit` to test how long it takes to multiply `my_array` by 2
(hint: use the `*` operator).

In [63]:
%%timeit
[item*2 for item in my_list]

1.09 ms ± 45.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

*Solution.*

In [64]:
%%timeit
my_array*2

5.4 μs ± 418 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

<span class="theorem-title">**Exercise 31**</span> What is faster:
multiplying an array by 2 or adding the array to itself?

*Solution.*

In [66]:
%%timeit
my_array + my_array

4.6 μs ± 226 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [67]:
%%timeit
my_array*2

4.8 μs ± 144 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

They take roughly the same time